// src/app/prodotti/data.ts

// —————————————————— TYPES ——————————————————
export type Condition = "nuovo" | "usato";

export type Category =
  | "trattori_gommati"
  | "trattori_cingolati"
  | "vigneto_frutteto"
  | "giardinaggio"
  | "movimento_terra"
  | "rimorchi"
  | "serbatoi"
  | "raccolta"
  | "boschive"
  | "fienagione";

export const CATEGORIES: Record<Category, string> = {
  trattori_gommati: "Trattori gommati",
  trattori_cingolati: "Trattori cingolati",
  vigneto_frutteto: "Vigneto / Frutteto",
  giardinaggio: "Macchine per il giardinaggio",
  movimento_terra: "Macchine movimento terra",
  rimorchi: "Rimorchi",
  serbatoi: "Serbatoi",
  raccolta: "Macchine da raccolta",
  boschive: "Macchine boschive",
  fienagione: "Macchine per fienagione",
};

// — Specifiche tecniche usate nel dettaglio
export interface ProductSpecs {
  tyresFrontSize?: string;
  tyresRearSize?: string;
  tyresFrontState?: string; // es. "30%"
  tyresRearState?: string; // es. "25%"
  transmission?: string; // es. "Meccanica", "Powershift"
  powerHp?: number;
  engineCyl?: number; // n° cilindri
  cab?: boolean; // cabina
  aircon?: boolean; // A/C
  year?: number;
  conditionNote?: string; // es. "Macchina da riparare"
  hours?: number; // ore macchina
}

export interface CatalogItem {
  id: string;
  slug: string; // /prodotti/[slug]
  title: string; // nome commerciale
  brand?: string;
  category: Category;
  condition: Condition; // nuovo | usato
  year?: number;
  hours?: number; // solo usato
  powerHp?: number;
  price?: number; // se assente o 0 => "Su richiesta"
  cover: string; // /public/images/catalog/...
  gallery?: string[]; // immagini extra
  badge?: string; // es. "Occasione", "Km 0"
  specs?: ProductSpecs; // usato dal dettaglio
  description?: string; // mini descrizione mostrata sotto la gallery
}

/* -------------------- TRATTORI (aggiornati) -------------------- */
export const ITEMS: CatalogItem[] = [
  // ——— GOMMATI (usato)
  {
    id: "mf-168",
    slug: "trattore-usato-massey-ferguson-mf-168",
    title: "Trattore usato Massey Ferguson MF 168",
    brand: "Massey Ferguson",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/masseyferguson.png",
    price: 3800,
    description:
      "Compatto e semplice da mantenere, ideale per piccole lavorazioni e traini leggeri. Meccanica affidabile e consumi ridotti.",
    specs: {
      tyresFrontSize: "6.00-16",
      tyresRearSize: "14.9-28",
      tyresFrontState: "20%",
      tyresRearState: "25%",
      transmission: "Meccanica",
      powerHp: 60,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 1974,
      conditionNote: "Discreto",
      hours: 14445,
    },
    year: 1974,
    hours: 14445,
    powerHp: 60,
  },
  {
    id: "fiat-640dt",
    slug: "trattore-usato-fiat-modello-640dt",
    title: "Trattore usato Fiat Modello 640DT",
    brand: "Fiat",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/fiat640.png",
    price: 5900,
    description:
      "Classico 4 cilindri con ottimo rapporto peso/potenza. Perfetto per trasporto e lavori in campo con attrezzature di media richiesta.",
    specs: {
      tyresFrontSize: "7.50-18",
      tyresRearSize: "16.9-30",
      tyresFrontState: "40%",
      tyresRearState: "35%",
      transmission: "Meccanica",
      powerHp: 64,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 1978,
      conditionNote: "Funzionante",
      hours: 8200,
    },
    year: 1978,
    hours: 8200,
    powerHp: 64,
  },
  {
    id: "lamborghini-700vdt",
    slug: "trattore-usato-lamborghini-700-vdt",
    title: "Trattore usato Lamborghini 700 VDT",
    brand: "Lamborghini",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/lamborghini700.png",
    price: 7900,
    description:
      "Versatile e robusto, adatto a lavorazioni generiche e al traino. Manutenzione semplice e ricambi disponibili.",
    specs: {
      tyresFrontSize: "11.2-24",
      tyresRearSize: "16.9-34",
      tyresFrontState: "35%",
      tyresRearState: "30%",
      transmission: "Meccanica",
      powerHp: 70,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 1985,
      conditionNote: "Buono",
      hours: 9650,
    },
    year: 1985,
    hours: 9650,
    powerHp: 70,
  },
  {
    id: "nh-tl80",
    slug: "trattore-usato-new-holland-tl-80",
    title: "Trattore usato New Holland TL 80",
    brand: "New Holland",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/newhollandtl80.png",
    price: 18000,
    description:
      "Trattore usato di marca New Holland modello TL 80, motore 4 cilindri completo di: attacchi attrezzi con ganci rapidi, 2 distributori idraulici posteriori con 4 uscite d’olio, supporto zavorre. Macchina da riparare in alcune sue parti.",
    specs: {
      tyresFrontSize: "380/70R24",
      tyresRearSize: "540/65R34",
      tyresFrontState: "30%",
      tyresRearState: "25%",
      transmission: "Meccanica",
      powerHp: 82,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 2005,
      conditionNote: "Macchina da riparare",
      hours: 7600,
    },
    year: 2005,
    hours: 7600,
    powerHp: 82,
  },
  {
    id: "nh-m160",
    slug: "trattore-usato-new-holland-m-160",
    title: "Trattore usato New Holland M 160",
    brand: "New Holland",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/new-holland-m-160.jpg",
    price: 32900,
    description:
      "Alta potenza e comfort con trasmissione Powershift. Ottimo per lavorazioni gravose in campo aperto e attrezzi esigenti.",
    specs: {
      tyresFrontSize: "420/70R28",
      tyresRearSize: "520/70R38",
      tyresFrontState: "55%",
      tyresRearState: "50%",
      transmission: "Powershift",
      powerHp: 160,
      engineCyl: 6,
      cab: true,
      aircon: true,
      year: 2001,
      conditionNote: "Revisionato",
      hours: 8900,
    },
    year: 2001,
    hours: 8900,
    powerHp: 160,
  },
  {
    id: "landini-landpower-135",
    slug: "trattore-usato-landini-landpower-135",
    title: "Trattore usato Landini Landpower 135",
    brand: "Landini",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/landini-landpower-135.jpg",
    price: 29900,
    description:
      "6 cilindri equilibrato, confortevole e affidabile. Ideale per fienagione, aratura e semina con attrezzature Isobus-ready.",
    specs: {
      tyresFrontSize: "420/70R28",
      tyresRearSize: "520/70R38",
      tyresFrontState: "60%",
      tyresRearState: "55%",
      transmission: "Powershift",
      powerHp: 135,
      engineCyl: 6,
      cab: true,
      aircon: true,
      year: 2015,
      conditionNote: "Ottimo",
      hours: 4200,
    },
    year: 2015,
    hours: 4200,
    powerHp: 135,
  },
  {
    id: "landini-technofarm-70dt",
    slug: "trattore-usato-landini-technofarm-70dt",
    title: "Trattore usato Landini Technofarm 70DT",
    brand: "Landini",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/landini-technofarm-70dt.jpg",
    price: 17900,
    description:
      "Compatto e pratico, con 4WD e idraulica efficiente. Perfetto per aziende miste e lavori quotidiani.",
    specs: {
      tyresFrontSize: "320/70R24",
      tyresRearSize: "420/70R30",
      tyresFrontState: "45%",
      tyresRearState: "40%",
      transmission: "Meccanica",
      powerHp: 70,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 2008,
      conditionNote: "Buono",
      hours: 6100,
    },
    year: 2008,
    hours: 6100,
    powerHp: 70,
  },
  {
    id: "fiat-70-66dt",
    slug: "trattore-usato-fiat-70-66-dt",
    title: "Trattore usato Fiat 70/66 DT",
    brand: "Fiat",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/fiat-70-66-dt.jpg",
    price: 13900,
    description:
      "Storico mulo da lavoro: semplice, economico e sempre pronto. Ottimo per trasporti e lavori con presa di forza.",
    specs: {
      tyresFrontSize: "11.2-24",
      tyresRearSize: "16.9-34",
      tyresFrontState: "35%",
      tyresRearState: "35%",
      transmission: "Meccanica",
      powerHp: 70,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 1990,
      conditionNote: "Funzionante",
      hours: 9800,
    },
    year: 1990,
    hours: 9800,
    powerHp: 70,
  },
  {
    id: "same-tb-85",
    slug: "trattore-usato-same-tb-85",
    title: "Trattore usato Same TB 85",
    brand: "Same",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/same-tb-85.jpg",
    price: 16900,
    description:
      "Compatto 85 CV con ottima maneggevolezza. Adatto a fienagione, spandiconcime e lavori aziendali quotidiani.",
    specs: {
      tyresFrontSize: "340/85R24",
      tyresRearSize: "420/85R34",
      tyresFrontState: "50%",
      tyresRearState: "45%",
      transmission: "Meccanica",
      powerHp: 85,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 2004,
      conditionNote: "Buono",
      hours: 7200,
    },
    year: 2004,
    hours: 7200,
    powerHp: 85,
  },
  {
    id: "nh-tl-100a",
    slug: "trattore-usato-new-holland-tl-100-a",
    title: "Trattore usato New Holland TL 100 A",
    brand: "New Holland",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/new-holland-tl-100a.jpg",
    price: 23900,
    description:
      "100 CV equilibrati con cabina confortevole. Perfetto per lavori misti e attività contoterzi leggere.",
    specs: {
      tyresFrontSize: "380/70R24",
      tyresRearSize: "480/70R34",
      tyresFrontState: "55%",
      tyresRearState: "50%",
      transmission: "Meccanica",
      powerHp: 100,
      engineCyl: 4,
      cab: true,
      aircon: false,
      year: 2007,
      conditionNote: "Ottimo",
      hours: 6800,
    },
    year: 2007,
    hours: 6800,
    powerHp: 100,
  },
  {
    id: "pasquali-565-ergo-780",
    slug: "trattore-usato-pasquali-565-ergo-7-80",
    title: "Trattore usato Pasquali 565 Ergo 7.80",
    brand: "Pasquali",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/pasquali-565-ergo-7-80.jpg",
    price: 6900,
    description:
      "Compatto e leggero, ideale per frutteti e lavorazioni in spazi stretti. Semplice e parsimonioso.",
    specs: {
      tyresFrontSize: "6.00-12",
      tyresRearSize: "8.3-20",
      tyresFrontState: "45%",
      tyresRearState: "40%",
      transmission: "Meccanica",
      powerHp: 20,
      engineCyl: 2,
      cab: false,
      aircon: false,
      year: 1998,
      conditionNote: "Buono",
      hours: 3100,
    },
    year: 1998,
    hours: 3100,
    powerHp: 20,
  },
  {
    id: "same-silver-130",
    slug: "trattore-usato-same-silver-130",
    title: "Trattore usato Same Silver 130",
    brand: "Same",
    category: "trattori_gommati",
    condition: "usato",
    cover: "/images/catalog/same-silver-130.jpg",
    price: 27900,
    description:
      "130 CV con Powershift e cabina climatizzata. Pensato per chi cerca produttività e comfort a costi contenuti.",
    specs: {
      tyresFrontSize: "420/70R28",
      tyresRearSize: "520/70R38",
      tyresFrontState: "60%",
      tyresRearState: "55%",
      transmission: "Powershift",
      powerHp: 130,
      engineCyl: 6,
      cab: true,
      aircon: true,
      year: 2003,
      conditionNote: "Ottimo",
      hours: 7400,
    },
    year: 2003,
    hours: 7400,
    powerHp: 130,
  },

  // ——— VIGNETO / FRUTTETO (usato)
  {
    id: "lamborghini-774-80n",
    slug: "trattore-usato-lamborghini-774-80n",
    title: "Trattore usato Lamborghini 774 80N",
    brand: "Lamborghini",
    category: "vigneto_frutteto",
    condition: "usato",
    cover: "/images/catalog/lamborghini-774-80n.jpg",
    price: 16900,
    description:
      "Versione stretta per filari, ottima maneggevolezza e visibilità. Pronto per frutteti e vigneti.",
    specs: {
      tyresFrontSize: "240/70R16",
      tyresRearSize: "320/70R24",
      tyresFrontState: "35%",
      tyresRearState: "35%",
      transmission: "Meccanica",
      powerHp: 75,
      engineCyl: 4,
      cab: false,
      aircon: false,
      year: 2008,
      conditionNote: "Buono",
      hours: 6400,
    },
    year: 2008,
    hours: 6400,
    powerHp: 75,
  },

  /* -------------------- ALTRI (con specs & descrizioni) -------------------- */
  {
    id: "merlo-p27-6",
    slug: "merlo-p27-6-usato",
    title: "Merlo P27.6",
    brand: "Merlo",
    category: "movimento_terra",
    condition: "usato",
    year: 2019,
    hours: 3100,
    price: 46500,
    cover: "/images/catalog/merlo-p27-6.jpg",
    description:
      "Sollevatore telescopico compatto, ideale per movimentazione in azienda. Cabina confortevole e ottima visibilità.",
    specs: {
      tyresFrontSize: "400/70-20",
      tyresRearSize: "400/70-20",
      tyresFrontState: "60%",
      tyresRearState: "60%",
      transmission: "Idrostatico",
      powerHp: 75,
      engineCyl: 4,
      cab: true,
      aircon: true,
      year: 2019,
      conditionNote: "Ottimo",
      hours: 3100,
    },
    powerHp: 75,
  },
  {
    id: "rimorchio-mazzotti-10t",
    slug: "rimorchio-mazzotti-10t-usato",
    title: "Rimorchio agricolo 10T",
    brand: "Mazzotti",
    category: "rimorchi",
    condition: "usato",
    year: 2012,
    price: 6900,
    cover: "/images/catalog/rimorchio-10t.jpg",
    description:
      "Cassone robusto con sponde e portata 10 tonnellate. Ottimo per trasporti aziendali e raccolti.",
    specs: {
      tyresFrontSize: "400/60-15.5",
      tyresRearSize: "400/60-15.5",
      tyresFrontState: "50%",
      tyresRearState: "50%",
      transmission: "—",
      powerHp: 0,
      engineCyl: 0,
      cab: false,
      aircon: false,
      year: 2012,
      conditionNote: "Buono",
      hours: 0,
    },
  },
  {
    id: "serbatoio-gpl-5000",
    slug: "serbatoio-5000-litri-nuovo",
    title: "Serbatoio 5000 L",
    brand: "Comap",
    category: "serbatoi",
    condition: "nuovo",
    price: 0,
    cover: "/images/catalog/serbatoio-5000.jpg",
    description:
      "Serbatoio nuovo da 5.000 litri per stoccaggio. Conforme alle normative vigenti, pronto all’installazione.",
    specs: {
      tyresFrontSize: "—",
      tyresRearSize: "—",
      tyresFrontState: "—",
      tyresRearState: "—",
      transmission: "—",
      powerHp: 0,
      engineCyl: 0,
      cab: false,
      aircon: false,
      year: new Date().getFullYear(),
      conditionNote: "Nuovo",
      hours: 0,
    },
  },
  {
    id: "falciatrice-fella",
    slug: "falciatrice-laterale-fella-usato",
    title: "Falciatrice laterale",
    brand: "Fella",
    category: "fienagione",
    condition: "usato",
    year: 2016,
    price: 3800,
    cover: "/images/catalog/falciatrice.jpg",
    description:
      "Barra di taglio efficiente e manutenzione semplice. Perfetta per la fienagione aziendale.",
    specs: {
      tyresFrontSize: "—",
      tyresRearSize: "—",
      tyresFrontState: "—",
      tyresRearState: "—",
      transmission: "PTO",
      powerHp: 0,
      engineCyl: 0,
      cab: false,
      aircon: false,
      year: 2016,
      conditionNote: "Buono",
      hours: 0,
    },
  },
  {
    id: "moto-sega-stihl",
    slug: "moto-sega-stihl-nuova",
    title: "Motosega professionale",
    brand: "Stihl",
    category: "boschive",
    condition: "nuovo",
    price: 0,
    cover: "/images/catalog/motosega.jpg",
    description:
      "Motosega professionale potente e bilanciata. Avviamento rapido e vibrazioni ridotte.",
    specs: {
      tyresFrontSize: "—",
      tyresRearSize: "—",
      tyresFrontState: "—",
      tyresRearState: "—",
      transmission: "Frizione centrifuga",
      powerHp: 8, // hp equivalenti ~ 6 kW
      engineCyl: 1,
      cab: false,
      aircon: false,
      year: new Date().getFullYear(),
      conditionNote: "Nuovo",
      hours: 0,
    },
    powerHp: 8,
  },
  {
    id: "raccoglitrice-mietitrebbia",
    slug: "raccoglitrice-mietitrebbia-usata",
    title: "Mietitrebbia 200 CV",
    brand: "Claas",
    category: "raccolta",
    condition: "usato",
    year: 2013,
    hours: 3900,
    price: 65900,
    cover: "/images/catalog/mietitrebbia.jpg",
    description:
      "Mietitrebbia 6 cilindri con elevata capacità operativa. Cabina confortevole e manutenzioni regolari.",
    specs: {
      tyresFrontSize: "800/65R32",
      tyresRearSize: "500/70R24",
      tyresFrontState: "55%",
      tyresRearState: "55%",
      transmission: "Idrostatico",
      powerHp: 200,
      engineCyl: 6,
      cab: true,
      aircon: true,
      year: 2013,
      conditionNote: "Ottimo",
      hours: 3900,
    },
    powerHp: 200,
  },
];
